services:
  - type: web
    name: h-and-i-store
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn ecommerce_manager.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.11.1
