services:
  - type: web
    name: h-and-i-store
    env: python
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.11.1

databases:
  - name: handistore
    databaseName: handistore
    user: handistore
