# Generated by Django 5.2.7 on 2025-12-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='due_date',
        ),
        migrations.AddField(
            model_name='debt',
            name='paid_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
