# Generated by Django 6.0.5 on 2026-06-06 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_cart_cartitem'),
        ('ecommerce', '0006_consignment_supplier_consignmentitem_expense_and_more'),
    ]

    operations = [
    ]
