# Generated by Django 5.2.9 on 2026-07-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_order_payment_status_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('paid', 'Paid')], default='pending_approval', max_length=20),
        ),
    ]
