# Generated by Django 5.2.9 on 2026-07-27 06:41

from django.db import migrations, models


def migrate_approved_to_paid(apps, schema_editor):
    Order = apps.get_model('ecommerce', 'Order')
    Order.objects.filter(payment_status='approved').update(payment_status='paid')


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_alter_order_payment_status'),
    ]

    operations = [
        migrations.RunPython(migrate_approved_to_paid, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('paid', 'Paid')], default='pending_approval', max_length=20),
        ),
    ]
