# Generated by Django 5.2.9 on 2026-07-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_notification_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mpesa_checkout_request_id',
            field=models.CharField(blank=True, help_text='M-Pesa STK Push CheckoutRequestID', max_length=100, null=True),
        ),
    ]
