# Generated by Django 5.2.9 on 2026-07-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_product_cost_price_product_featured_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, max_length=110),
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('name', 'category')},
        ),
    ]
