# Generated by Django 5.2.9 on 2026-09-14 13:03

import ecommerce.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_alter_brand_name_alter_brand_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=ecommerce.storage_backends.SupabaseMediaStorage('profile-media'), upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=ecommerce.storage_backends.SupabaseMediaStorage('product-media', public=True), upload_to='products/'),
        ),
    ]
